name: cloudbabbel

on:
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          sudo ./installAwsCli.sh

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Public SSH Key
        run: |
          path=$(pwd)
          echo $path
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $path/id_rsa.pub

      - name: install treehouses
        run: |
          #sudo apt update  
          sudo apt install tor
          sudo npm install -g @treehouses/cli

      - name: start luftbllon
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1 
          aws configure set default.output json
          aws configure get output
          sudo bash init.sh -g

      - name: open seasame
        run: |
          #sudo apt update  
          sudo treehouses tor add 22
          sudo treehouses tor
          sudo treehouses tor notice now
          sudo treehouses sshkey github adduser dogi
          sudo treehouses sshkey github adduser hirotochigi
          echo "shh only dreams"
          ls -al
          echo -------------
          echo -------------
          echo -------------
          ls -alR
          sleep 1200

      - name: Cleanup Step
        if: cancelled() || failure()
        run: |
          sudo bash delete.sh luftballon
