name: cloudbabbel

on: 
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: open seasame
        run: |
          #sudo apt update  
          sudo apt install tor
          sudo npm install -g @treehouses/cli
          sudo treehouses tor add 22
          sudo treehouses tor
          sudo treehouses tor notice now
          sudo treehouses sshkey github adduser dogi
          sudo treehouses sshkey github adduser hirotochigi
          echo "shh only dreams"
          ls -al
          echo -------------
          echo -------------
          echo -------------
          ls -alR
          sleep 1200
            
